<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-CLUMQLOR" failures="1" tests="2" name="com.FrameWork.TestScript_5" time="0.007" errors="0" timestamp="2024-02-22T13:49:21 IST" skipped="0">
  <testcase classname="com.FrameWork.TestScript_5" name="loginPage" time="0.001">
    <system-out>
      <![CDATA[Login page Executed]]>
    </system-out>
  </testcase> <!-- loginPage -->
  <testcase classname="com.FrameWork.TestScript_5" name="signUp" time="0.006">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.FrameWork.TestScript_5.signUp(TestScript_5.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[SignUp method Executed]]>
    </system-out>
  </testcase> <!-- signUp -->
  <system-out>
    <![CDATA[Script02
Script_01
TestScript_01
TestScript_02
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Create Account Method Executed
Delete Account Executed
M1 method is executed 
M2 method is executed 
M3 method is executed 
M4 method is executed 
m5 method is executed
Sign up method Executed
Login page Executed
SignUp method Executed
Login page Executed
Admin1
Manager1
Admin2
manager2
Edit Account method Executed
Read Account method Executed
Create Account Method Executed]]>
  </system-out>
</testsuite> <!-- com.FrameWork.TestScript_5 -->
